version = 1

test_patterns = ["tests/**"]

[[analyzers]]
name = "docker"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "csharp"

[[transformers]]
name = "dotnet-format"