name: Release Docker image

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REPOSITORY_URL }}}
        username: ${{ secrets.DOCKER_REPOSITORY_USERNAME } }}
        password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY_URL }}/${{ secrets.DOCKER_REPOSITORY_USERNAME }}/forehead-api:${{ github.sha }},${{ secrets.DOCKER_REPOSITORY_URL }}/${{ secrets.DOCKER_REPOSITORY_USERNAME }}/forehead-api:latest
